In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xlrd8

In [2]:
book1 = xlrd.open_workbook('VSAT.xlsx')
working_sheet_from_iocl = book1.sheet_by_index(2)
headings = working_sheet_from_iocl.row_values(0)

In [3]:
print(working_sheet_from_iocl.row_values(0))

['VSAT ID', 'SAP PO ', 'RO SAP CODE', 'RO NAME', 'VSAT IP', 'SITE ADDRESS', 'DO NAME', 'INVOICE QTR', 'COMMISSIONING DATE', 'START DATE', 'END DATE', 'DAYS', 'SERVICE PROVIDING STATE', 'State of Service Receipt', 'H/W  RENTAL INVOICE NO', 'INVOICE DATE', 'HW Rate', 'H/W RENTAL', "Jan '20 uptime %", 'Deduction as per SLA', 'Payout %', "Feb '20 uptime %", 'Deduction as per SLA', 'Payout %', "March '20 uptime %", 'Deduction as per SLA', 'Payout %', 'Total Deductions for SLA', 'HW BASIC', 'HW GST', 'HW SLA Deduction inc GST', 'HW Calculated  Amount', 'HW Total From Vendor', 'HW Amount to be paid (Minimum of Calculated and Vendor', '', 'B/W  RENTAL INVOICE NO', 'INVOICE DATE', 'BW Rate / Month', 'B/W RENTAL', "Jan '20 uptime %", 'Deduction as per SLA', 'Payout %', "Feb '20 uptime %", 'Deduction as per SLA', 'Payout %', "March '20 uptime %", 'Deduction as per SLA', 'Payout %', 'Total Deductions for SLA', 'BW BASIC', 'BW GST', 'BW SLA Deduction inc GST', 'BW Calculated Amount', 'BW Total from Vendor', 'BW Amount to be paid (Minimum of Calculated and Vendor']

In [4]:
df=pd.read_excel('VSAT.xlsx',sheet_name='Working Sheet from IOC')

In [5]:
df1 = df[['RO SAP CODE','RO NAME']]
df1

    RO SAP CODE                                 RO NAME
0        137990        BROADWAY-SERVICE-STATION--I-420-
1        273357         SWASTIK FUEL REFILL CENTRE(KSK)
2        140227                    STAR SERVICE STATION
3        292019                        GANPATI SQ.F/CEN
4        295158                       BASAK AUTOMOBILES
5        140175               KAMAKSHYA SERVICE STATION
6        267503     DHRITISHREE KISAN SEVA KENDRA [KSK]
7        246679         SABITA FUEL & AGRO AGENCY [KSK]
8        206671                AL KUDRAT-E-NISHAN (AOD)
9        208012           Baba Lokenath Service Station
10       138769       PAUL BROTHERS SERVICE STN (I-501)
11       138820           SARKAR SERVICE STATION(I-528)
12       190566                 CHANDIMATA AUTO SERVICE
13       273412     RANGDHAMALI KISAN SEVA KENDRA [KSK]
14       264848                             JANAGAN KSK
15       220588              MA TARA KISHAN SEVA KENDRA
16       295171                    MINA SERVICE STATION
17       245421             MAADURGA FUEL SERVICE (KSK)
18       148060                 SONAPUR SERVICE STATION
19       209255     BABA TARAKNATH SERVICESTATION(I-731
20       217631  RELIABLE FUELING STATION (COCO,PANDUA)
21       138592           BANIK SERVICE STATION (I-409)
22       138627              DEVIYA FUEL CENTRE (I-434)
23       139914                                  FILLCO
24       252578         LISSA COMPANY KISAN SEVA KENDRA
25       256543         RAHAMAN KISAN SEVA KENDRA [KSK]
26       138042         JAUNPUR SERVICE STATION (I-474)
27       309334         COCO CHOPRA (ADHOC TERAI FUELS)
28       269513                         U S FUELS [KSK]

In [6]:
df1['Payment Raise in XYZ quarter'] = df['HW BASIC'] + df['HW GST'] + df['BW BASIC'] + df['BW GST']
df1['SLA Deduction in XYZ quarter'] = df['HW SLA Deduction inc GST'] + df['BW SLA Deduction inc GST']
df1['Payment Made in XYZ quarter'] = df['HW Amount to be paid (Minimum of Calculated and Vendor'] + df['BW Amount to be paid (Minimum of Calculated and Vendor']

C:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [7]:
df1.set_index('RO SAP CODE',inplace=True)
df1

,RO NAME,Payment Raise in XYZ quarter,SLA Deduction in XYZ quarter,Payment Made in XYZ quarter
RO SAP CODE,,,,
137990,BROADWAY-SERVICE-STATION--I-420-,4159.6416,0.00000,4159.64160
273357,SWASTIK FUEL REFILL CENTRE(KSK),4159.6416,0.00000,4159.64160
140227,STAR SERVICE STATION,4159.6416,0.00000,4159.64160
292019,GANPATI SQ.F/CEN,4159.6416,0.00000,4159.64160
295158,BASAK AUTOMOBILES,4159.6416,0.00000,4159.64160
140175,KAMAKSHYA SERVICE STATION,4159.6416,69.32736,4090.31424
267503,DHRITISHREE KISAN SEVA KENDRA [KSK],4159.6416,0.00000,4159.64160
246679,SABITA FUEL & AGRO AGENCY [KSK],4159.6416,0.00000,4159.64160
206671,AL KUDRAT-E-NISHAN (AOD),4159.6416,0.00000,4159.64160
208012,Baba Lokenath Service Station,4159.6416,0.00000,4159.64160
138769,PAUL BROTHERS SERVICE STN (I-501),4159.6416,69.32736,4090.31424
138820,SARKAR SERVICE STATION(I-528),4159.6416,0.00000,4159.64160
190566,CHANDIMATA AUTO SERVICE,4159.6416,138.65472,4020.98688
273412,RANGDHAMALI KISAN SEVA KENDRA [KSK],4159.6416,0.00000,4159.64160
264848,JANAGAN KSK,4159.6416,0.00000,4159.64160
220588,MA TARA KISHAN SEVA KENDRA,4159.6416,4159.64160,0.00000
295171,MINA SERVICE STATION,4159.6416,0.00000,4159.64160
245421,MAADURGA FUEL SERVICE (KSK),4159.6416,0.00000,4159.64160
148060,SONAPUR SERVICE STATION,4159.6416,0.00000,4159.64160
209255,BABA TARAKNATH SERVICESTATION(I-731,4159.6416,0.00000,4159.64160
217631,"RELIABLE FUELING STATION (COCO,PANDUA)",4159.6416,0.00000,4159.64160
138592,BANIK SERVICE STATION (I-409),4159.6416,415.96416,3743.67744
138627,DEVIYA FUEL CENTRE (I-434),4159.6416,0.00000,4159.64160
139914,FILLCO,4159.6416,0.00000,4159.64160
252578,LISSA COMPANY KISAN SEVA KENDRA,4159.6416,0.00000,4159.64160
256543,RAHAMAN KISAN SEVA KENDRA [KSK],4159.6416,69.32736,4090.31424
138042,JAUNPUR SERVICE STATION (I-474),4159.6416,0.00000,4159.64160
309334,COCO CHOPRA (ADHOC TERAI FUELS),4159.6416,0.00000,4159.64160
269513,U S FUELS [KSK],4159.6416,1386.54720,2773.09440

In [8]:
df1.to_excel('AUTOMATED VSAT Report(1).xlsx',sheet_name='Automated Report')

In [9]:
df1

,RO NAME,Payment Raise in XYZ quarter,SLA Deduction in XYZ quarter,Payment Made in XYZ quarter
RO SAP CODE,,,,
137990,BROADWAY-SERVICE-STATION--I-420-,4159.6416,0.00000,4159.64160
273357,SWASTIK FUEL REFILL CENTRE(KSK),4159.6416,0.00000,4159.64160
140227,STAR SERVICE STATION,4159.6416,0.00000,4159.64160
292019,GANPATI SQ.F/CEN,4159.6416,0.00000,4159.64160
295158,BASAK AUTOMOBILES,4159.6416,0.00000,4159.64160
140175,KAMAKSHYA SERVICE STATION,4159.6416,69.32736,4090.31424
267503,DHRITISHREE KISAN SEVA KENDRA [KSK],4159.6416,0.00000,4159.64160
246679,SABITA FUEL & AGRO AGENCY [KSK],4159.6416,0.00000,4159.64160
206671,AL KUDRAT-E-NISHAN (AOD),4159.6416,0.00000,4159.64160
208012,Baba Lokenath Service Station,4159.6416,0.00000,4159.64160
138769,PAUL BROTHERS SERVICE STN (I-501),4159.6416,69.32736,4090.31424
138820,SARKAR SERVICE STATION(I-528),4159.6416,0.00000,4159.64160
190566,CHANDIMATA AUTO SERVICE,4159.6416,138.65472,4020.98688
273412,RANGDHAMALI KISAN SEVA KENDRA [KSK],4159.6416,0.00000,4159.64160
264848,JANAGAN KSK,4159.6416,0.00000,4159.64160
220588,MA TARA KISHAN SEVA KENDRA,4159.6416,4159.64160,0.00000
295171,MINA SERVICE STATION,4159.6416,0.00000,4159.64160
245421,MAADURGA FUEL SERVICE (KSK),4159.6416,0.00000,4159.64160
148060,SONAPUR SERVICE STATION,4159.6416,0.00000,4159.64160
209255,BABA TARAKNATH SERVICESTATION(I-731,4159.6416,0.00000,4159.64160
217631,"RELIABLE FUELING STATION (COCO,PANDUA)",4159.6416,0.00000,4159.64160
138592,BANIK SERVICE STATION (I-409),4159.6416,415.96416,3743.67744
138627,DEVIYA FUEL CENTRE (I-434),4159.6416,0.00000,4159.64160
139914,FILLCO,4159.6416,0.00000,4159.64160
252578,LISSA COMPANY KISAN SEVA KENDRA,4159.6416,0.00000,4159.64160
256543,RAHAMAN KISAN SEVA KENDRA [KSK],4159.6416,69.32736,4090.31424
138042,JAUNPUR SERVICE STATION (I-474),4159.6416,0.00000,4159.64160
309334,COCO CHOPRA (ADHOC TERAI FUELS),4159.6416,0.00000,4159.64160
269513,U S FUELS [KSK],4159.6416,1386.54720,2773.09440